spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mauser
    password: mauserpass
    url: jdbc:mysql://mysql-db:3306/ma
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
